config/routes.php
<?php
/**
 * Routes configuration
 *
 * In this file, you set up routes to your controllers and their actions.
 * Routes are very important mechanism that allows you to freely connect
 * different URLs to chosen controllers and their actions (functions).
 *
 * CakePHP(tm) : Rapid Development Framework (http://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 * @link          http://cakephp.org CakePHP(tm) Project
 * @license       http://www.opensource.org/licenses/mit-license.php MIT License
 */

use Cake\Core\Plugin;
use Cake\Routing\RouteBuilder;
use Cake\Routing\Router;

/**
 * The default class to use for all routes
 *
 * The following route classes are supplied with CakePHP and are appropriate
 * to set as the default:
 *
 * - Route
 * - InflectedRoute
 * - DashedRoute
 *
 * If no call is made to `Router::defaultRouteClass()`, the class used is
 * `Route` (`Cake\Routing\Route\Route`)
 *
 * Note that `Route` does not do any inflections on URLs which will result in
 * inconsistently cased URLs when used with `:plugin`, `:controller` and
 * `:action` markers.
 *
 */
Router::defaultRouteClass('DashedRoute');

Router::scope('/', function (RouteBuilder $routes) {
    /**
     * Here, we are connecting '/' (base path) to a controller called 'Pages',
     * its action called 'display', and we pass a param to select the view file
     * to use (in this case, src/Template/Pages/home.ctp)...
     */
   
   
    /**
     * ...and connect the rest of 'Pages' controller's URLs.
     */

    $routes->connect('/', ['controller' => 'Indicadores', 'action' => 'index']);
    $routes->connect('/getconvenio', ['controller' => 'Atendimentos', 'action' => 'convenios']);
    $routes->connect('/proc/*', ['controller' => 'Atendimentos', 'action' => 'proc']);
    $routes->connect('/deletaritens/*', ['controller' => 'Atendimentos', 'action' => 'removeitem']);
    $routes->connect('/cadclient/*', ['controller' => 'Clientes', 'action' => 'nadd']);
    $routes->connect('/findClientes/*', ['controller' => 'Clientes', 'action' => 'fill']);
    $routes->connect('/valores/*', ['controller' => 'Atendimentos', 'action' => 'getvalores']);
    $routes->connect('/configuracoes/*', ['controller' => 'Configuracoes', 'action' => 'edit']);
    $routes->extensions(['pdf', 'json']);
	
	 $routes->connect('/pages/*', ['controller' => 'Pages', 'action' => 'display']);

    /**
     * Connect catchall routes for all controllers.
     *
     * Using the argument `DashedRoute`, the `fallbacks` method is a shortcut for
     *    `$routes->connect('/:controller', ['action' => 'index'], ['routeClass' => 'DashedRoute']);`
     *    `$routes->connect('/:controller/:action/*', [], ['routeClass' => 'DashedRoute']);`
     *
     * Any route class can be used with this method, such as:
     * - DashedRoute
     * - InflectedRoute
     * - Route
     * - Or your own route class
     *
     * You can remove these routes once you've connected the
     * routes you want in your application.
     */
    $routes->fallbacks('DashedRoute');
});

/**
 * Load all plugin routes.  See the Plugin documentation on
 * how to customize the loading of plugin routes.
 */
Plugin::routes();

src/Model/Table/ClienteLigacoesTable.php
<?php
namespace App\Model\Table;

use App\Model\Entity\ClienteLigaco;
use Cake\Event\Event;
use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Routing\Router;
use Cake\Validation\Validator;
use DateTime;
use Cake\Datasource\EntityInterface;
use Cake\ORM\TableRegistry;
/**
 * ClienteLigacoes Model
 *
 * @property \Cake\ORM\Association\BelongsTo $Clientes
 * @property \Cake\ORM\Association\BelongsTo $ParentClienteLigacoes
 * @property \Cake\ORM\Association\BelongsTo $GrauParentescos
 * @property \Cake\ORM\Association\BelongsTo $SituacaoCadastros
 * @property \Cake\ORM\Association\BelongsTo $Users
 * @property \Cake\ORM\Association\HasMany $ChildClienteLigacoes
 */
class ClienteLigacoesTable extends Table
{

    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->table('cliente_ligacoes');
        $this->displayField('id');
        $this->primaryKey('id');

        $this->addBehavior('Timestamp');

        $this->belongsTo('Clientes', [
            'foreignKey' => 'cliente_id',
            'joinType' => 'INNER'
        ]);
        $this->belongsTo('ParentClienteLigacoes', [
            'className' => 'Clientes',
            'foreignKey' => 'parent_id'
        ]);
        $this->belongsTo('GrauParentescos', [
            'foreignKey' => 'grau_id',
            'joinType' => 'INNER'
        ]);
        $this->belongsTo('SituacaoCadastros', [
            'foreignKey' => 'situacao_id',
            'joinType' => 'INNER'
        ]);
        $this->belongsTo('Users', [
            'foreignKey' => 'user_id',
            'joinType' => 'INNER'
        ]);
        $this->hasMany('ChildClienteLigacoes', [
            'className' => 'ClienteLigacoes',
            'foreignKey' => 'parent_id'
        ]);
    }

    /**
     * Default validation rules.
     *
     * @param \Cake\Validation\Validator $validator Validator instance.
     * @return \Cake\Validation\Validator
     */
    public function validationDefault(Validator $validator)
    {
        $validator
            ->integer('id')
            ->allowEmpty('id', 'create');

        $validator
            ->requirePresence('parent_id')
            ->notEmpty('parent_id', 'create');

        $validator
            ->requirePresence('grau_id')
            ->notEmpty('grau_id', 'create');

        return $validator;
    }

    /**
     * Returns a rules checker object that will be used for validating
     * application integrity.
     *
     * @param \Cake\ORM\RulesChecker $rules The rules object to be modified.
     * @return \Cake\ORM\RulesChecker
     */
    public function buildRules(RulesChecker $rules)
    {
        $rules->add($rules->existsIn(['cliente_id'], 'Clientes'));
        $rules->add($rules->existsIn(['grau_id'], 'GrauParentescos'));
        return $rules;
    }

    public function beforeFind(Event $event,Query $queryData)
    {
      $outer = Router::getRequest();
     if($outer->controller=='ClienteLigacoes') {
              $queryData->where(['ClienteLigacoes.situacao_id' => 1]);
    if (!empty($outer->query)) {
           foreach ($outer->query as $key => $value) {
                if (!empty($value) && substr_count($key, '__') == 1) {
                    if(substr_count($value, '/')){
                          if(substr_count($value, ':')){
                                $data = new DateTime();
                                $value = $data->createFromFormat('d/m/Y H:i',$value);
                                $queryData->andWhere([str_replace('__', '.', $key) => $value]);
                          }else{
                                $value = implode('-', array_reverse(explode('/', $value)));
                                $queryData->andWhere([str_replace('__', '.', $key) => $value]);
                          }
                    }else{
                                $queryData->andWhere([str_replace('__', '.', $key) => $value]);
                    }
                }
           }
        }
     }
       return $queryData;
    }


    public function beforeSave(Event $event)
    {
        $entity = $event->data['entity'];
        if($entity->isNew()) {
                $entity->situacao_id = 1;
                  if (!empty($_SESSION['Auth']['User']['id'])) {
                      $entity->user_id = $_SESSION['Auth']['User']['id'];
                 }
         }
        return true;
    }


}

src/Template/ClienteLigacoes/add.ctp
<div class="this-place">
    <div class="wrapper white-bg page-heading">
        <div class="col-lg-9">
            <h2>Cliente</h2>
            <ol class="breadcrumb">
                <li>Vínculos</li>
                <li class="active">
                    <strong> Cadastrar </strong>
                </li>
            </ol>
        </div>
        <div class="clearfix"></div>
    </div>
    <div class="wrapper wrapper-content area area_pront">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-content">
                        <div class="clienteLigacoes form">
                            <?= $this->Form->create($clienteLigaco) ?>
                            <fieldset>
                                <?php
                                if(!empty($cliente_id)){
                                    echo $this->Form->input('cliente_id', ['type' => 'hidden', 'value' => $cliente_id]);
                                }else{
                                    echo "<div class='col-md-6'>";
                                    echo $this->Form->input('cliente_id', ['data' => 'select', 'controller' => 'clientes', 'action' => 'fill']);
                                    echo "</div>";
                                }
                                echo "<div class='col-md-6'>";
                                echo $this->Form->input('parent_id', ['label'=>'Vínculo - (Prontuário/Nome)','data' => 'select', 'controller' => 'clientes', 'action' => 'fill-prontuario']);
                                echo "</div>";

                                echo "<div class='col-md-6'>";
                                echo $this->Form->input('grau_id', ['options'=>$grau,'empty'=>'selecione']);
                                echo "</div>";

                                ?>

                            </fieldset>
                            <div class="col-md-12 text-right">
                                <?= $this->Form->submit(__('Salvar'), ['class' => 'btn btn-primary']) ?>
                            </div>
                            <div class="clearfix"></div>
                            <?= $this->Form->end() ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

src/Template/ClienteLigacoes/all.ctp
<div class="this-place">
    <div class="wrapper white-bg page-heading">
        <div class="col-lg-9">
            <h2>Pacientes</h2>
            <ol class="breadcrumb">
                <li>pacientes</li>
                <li class="active">
                    <strong>Vínculos</strong>
                </li>
            </ol>
        </div>
        <div class="clearfix"></div>
    </div>

    <div class="wrapper wrapper-content area_pront">
        <div class="row">
            <div class="col-lg-12">
                <div class="text-right">
                    <p>
                        <?= $this->Html->link($this->Html->icon('plus') . ' Novo vínculo', ['action' => 'nadd','?'=>['cliente_id'=>$cliente_id]], ['data-toggle' => 'tooltip', 'data-placement' => 'bottom', 'title' => 'Cadastrar Vínculo', 'class' => 'btn btn-primary', 'escape' => false]) ?>
                    </p>
                </div>

                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5><?= __('Cliente Ligacoes') ?></h5>
                    </div>
                    <div class="ibox-content">
                        <div class="clearfix">
                            <div class="table-responsive">
                                <table class="table table-hover">
                                    <thead>
                                    <tr>
                                        <th><?= $this->Paginator->sort('parent_id',['label'=>'Vínculo']) ?></th>
                                        <th><?= $this->Paginator->sort('grau_id') ?></th>
                                        <th><?= $this->Paginator->sort('created', ['label' => 'Dt. Criação']) ?></th>
                                        <th><?= $this->Paginator->sort('modified', ['label' => 'Última Atualização']) ?></th>
                                        <th class="actions"><?= __('Ações') ?></th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <?php foreach ($clienteLigacoes as $clienteLigaco): ?>
                                        <tr>
                                            <td><?= $clienteLigaco->has('parent_cliente_ligaco') ? $this->Html->link($clienteLigaco->parent_cliente_ligaco->nome, ['controller' => 'Clientes', 'action' => 'view', $clienteLigaco->parent_cliente_ligaco->id],['target'=>'_blank','listen'=>'f']) : '' ?></td>
                                            <td><?= $clienteLigaco->has('grau_parentesco') ? $clienteLigaco->grau_parentesco->nome : '' ?></td>
                                            <td><?= h($clienteLigaco->created) ?></td>
                                            <td><?= h($clienteLigaco->modified) ?></td>
                                            <td class="actions">
                                                <?= $this->Html->link($this->Html->icon('remove'), '#Javascript:void(0)', ['onclick'=>'Deletar(\'clienteLigacoes\','.$clienteLigaco->id.',\'carregarAba\','.$cliente_id.')','toggle'=>'tooltip','data-placement'=>'bottom','title'=>'Deletar','escape' => false,'class'=>'btn btn-xs btn-danger','listen'=>'f']) ?>
                                            </td>
                                        </tr>
                                    <?php endforeach; ?>
                                    </tbody>
                                </table>
                                <div style="text-align:center">
                                    <div class="paginator">
                                        <ul class="pagination">
                                            <?= $this->Paginator->prev($this->Html->icon('chevron-left'), ['escape' => false]) ?>
                                            <?= $this->Paginator->numbers() ?>
                                            <?= $this->Paginator->next($this->Html->icon('chevron-right'), ['escape' => false]) ?>
                                        </ul>
                                        <p><?= $this->Paginator->counter() ?></p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

src/Template/ClienteLigacoes/edit.ctp
<div class="this-place">
    <div class="wrapper white-bg page-heading">
        <div class="col-lg-9">
            <h2>Cliente Ligacoes</h2>
            <ol class="breadcrumb">
                <li>Cliente Ligacoes</li>
                <li class="active">
                    <strong> Editar Cliente Ligacoes
                    </strong>
                </li>
            </ol>
        </div>
        <div class="clearfix"></div>
    </div>
    <div class="wrapper wrapper-content area area_pront">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-content">
                        <div class="clienteLigacoes form">
                            <?= $this->Form->create($clienteLigaco) ?>
                            <fieldset>
                                <legend><?= __('Editar Cliente Ligaco') ?></legend>
                                <?php
                                echo $this->Form->input('cliente_id', ['type' => 'hidden',  'value' => $clienteLigaco->cliente_id]);

                                echo "<div class='col-md-6'>";
                                echo $this->Form->input('parent_id', ['data' => 'select', 'controller' => 'clientes', 'action' => 'fill', 'data-value' => $clienteLigaco->parent_id]);
                                echo "</div>";
                                echo "<div class='col-md-6'>";
                                echo $this->Form->input('grau_id', ['options' => $grau, 'empty' => 'selecione']);
                                echo "</div>";
                                ?>

                            </fieldset>
                            <div class="col-md-12 text-right">
                                <?= $this->Form->submit(__('Salvar'), ['class' => 'btn btn-primary']) ?>
                            </div>
                            <div class="clearfix"></div>
                            <?= $this->Form->end() ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

src/Template/ClienteLigacoes/index.ctp
<div class="this-place">
    <div class="wrapper white-bg page-heading">
        <div class="col-lg-9">
            <h2>Pacientes</h2>
            <ol class="breadcrumb">
                <li>pacientes</li>
                <li class="active">
                    <strong>Vínculos</strong>
                </li>
            </ol>
        </div>
        <div class="clearfix"></div>
    </div>

    <div class="wrapper wrapper-content area">
        <div class="row">
            <div class="col-lg-12">
                <div class="text-right">
                    <p>
                        <?= $this->Html->link($this->Html->icon('plus') . ' Novo vínculo', ['action' => 'add','?'=>['cliente_id'=>$cliente_id]], ['data-toggle' => 'tooltip', 'data-placement' => 'bottom', 'title' => 'Cadastrar Vínculo', 'class' => 'btn btn-primary', 'escape' => false]) ?>
                    </p>
                </div>

                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5><?= __('Cliente Ligacoes') ?></h5>
                    </div>
                    <div class="ibox-content">
                        <div class="clearfix">
                            <div class="table-responsive">
                                <table class="table table-hover">
                                    <thead>
                                    <tr>
                                        <th><?= $this->Paginator->sort('parent_id',['label'=>'Vínculo']) ?></th>
                                        <th><?= $this->Paginator->sort('grau_id') ?></th>
                                        <th><?= $this->Paginator->sort('created', ['label' => 'Dt. Criação']) ?></th>
                                        <th><?= $this->Paginator->sort('modified', ['label' => 'Última Atualização']) ?></th>
                                        <th class="actions"><?= __('Ações') ?></th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <?php foreach ($clienteLigacoes as $clienteLigaco): ?>
                                        <tr>
                                            <td><?= $clienteLigaco->has('parent_cliente_ligaco') ? $this->Html->link($clienteLigaco->parent_cliente_ligaco->nome, ['controller' => 'Clientes', 'action' => 'view', $clienteLigaco->parent_cliente_ligaco->id],['target'=>'_blank','listen'=>'f']) : '' ?></td>
                                            <td><?= $clienteLigaco->has('grau_parentesco') ? $clienteLigaco->grau_parentesco->nome : '' ?></td>
                                            <td><?= h($clienteLigaco->created) ?></td>
                                            <td><?= h($clienteLigaco->modified) ?></td>
                                            <td class="actions">
                                                <?= $this->Html->link($this->Html->icon('remove'), '#Javascript:void(0)', ['onclick' => 'Deletar(\'clienteLigacoes\',' . $clienteLigaco->id . ',recarregar)', 'toggle' => 'tooltip', 'data-placement' => 'bottom', 'title' => 'Deletar', 'escape' => false, 'class' => 'btn btn-xs btn-danger', 'listen' => 'f']) ?>
                                            </td>
                                        </tr>
                                    <?php endforeach; ?>
                                    </tbody>
                                </table>
                                <div style="text-align:center">
                                    <div class="paginator">
                                        <ul class="pagination">
                                            <?= $this->Paginator->prev($this->Html->icon('chevron-left'), ['escape' => false]) ?>
                                            <?= $this->Paginator->numbers() ?>
                                            <?= $this->Paginator->next($this->Html->icon('chevron-right'), ['escape' => false]) ?>
                                        </ul>
                                        <p><?= $this->Paginator->counter() ?></p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

src/Template/ClienteLigacoes/nadd.ctp
<div class="this-place">
    <div class="wrapper white-bg page-heading">
        <div class="col-lg-9">
            <h2>Cliente</h2>
            <ol class="breadcrumb">
                <li>Vínculos</li>
                <li class="active">
                    <strong> Cadastrar </strong>
                </li>
            </ol>
        </div>
        <div class="clearfix"></div>
    </div>
    <div class="wrapper wrapper-content area_pront">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-content">
                        <div class="clienteLigacoes form">
                            <?= $this->Form->create($clienteLigaco,['id'=>'form-vinculo']) ?>
                            <fieldset>
                                <?php
                                if(!empty($cliente_id)){
                                    echo $this->Form->input('cliente_id', ['type' => 'hidden', 'value' => $cliente_id]);
                                }else{
                                    echo "<div class='col-md-6'>";
                                    echo $this->Form->input('cliente_id', ['data' => 'select', 'controller' => 'clientes', 'action' => 'fill']);
                                    echo "</div>";
                                }
                                echo "<div class='col-md-6'>";
                                echo $this->Form->input('parent_id', ['label'=>'Vínculo - (Prontuário/Nome)','data' => 'select', 'controller' => 'clientes', 'action' => 'fill-prontuario']);
                                echo "</div>";

                                echo "<div class='col-md-6'>";
                                echo $this->Form->input('grau_id', ['options'=>$grau,'empty'=>'selecione']);
                                echo "</div>";

                                ?>

                            </fieldset>
                            <div class="col-md-12 text-right">
                                <?= $this->Form->submit(__('Salvar'), ['class' => 'btn btn-primary','onclick' => 'EnviarForm(\'form-vinculo\')']) ?>
                            </div>
                            <div class="clearfix"></div>
                            <?= $this->Form->end() ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

src/Template/ClienteLigacoes/view.ctp
<div class="this-place">
<div class="wrapper white-bg page-heading">
    <div class="col-lg-9">
        <h2>Cliente Ligacoes</h2>
        <ol class="breadcrumb">
            <li>Cliente Ligacoes</li>
            <li class="active">
                <strong>Litagem de Cliente Ligacoes</strong>
            </li>
        </ol>
    </div>
    <div class="clearfix"></div>
</div>
<div class="wrapper wrapper-content area area_pront">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-content">
                    <div class="table-responsive">
                        <h3>Detalhes Cliente Ligacoes</h3>
                        <table class="table table-hover">
                            <tr>
                                                                <th><?= __('Cliente') ?></th>
                                                                <td><?= $clienteLigaco->has('cliente') ? $this->Html->link($clienteLigaco->cliente->nome, ['controller' => 'Clientes', 'action' => 'view', $clienteLigaco->cliente->id]) : '' ?></td>
                            </tr>
                            <tr>
                                                                <th><?= __('Parent Cliente Ligaco') ?></th>
                                                                <td><?= $clienteLigaco->has('parent_cliente_ligaco') ? $this->Html->link($clienteLigaco->parent_cliente_ligaco->id, ['controller' => 'ClienteLigacoes', 'action' => 'view', $clienteLigaco->parent_cliente_ligaco->id]) : '' ?></td>
                            </tr>
                            <tr>
                                                                <th><?= __('Grau Parentesco') ?></th>
                                                                <td><?= $clienteLigaco->has('grau_parentesco') ? $this->Html->link($clienteLigaco->grau_parentesco->nome, ['controller' => 'GrauParentescos', 'action' => 'view', $clienteLigaco->grau_parentesco->id]) : '' ?></td>
                            </tr>
                            <tr>
                                                                <th><?= __('Situação Cadastro') ?></th>
                                                                <td><?= $clienteLigaco->has('situacao_cadastro') ? $this->Html->link($clienteLigaco->situacao_cadastro->nome, ['controller' => 'SituacaoCadastros', 'action' => 'view', $clienteLigaco->situacao_cadastro->id]) : '' ?></td>
                            </tr>
                            <tr>
                                                                <th><?= __('Quem Cadastrou') ?></th>
                                                                <td><?= $clienteLigaco->has('user') ? $this->Html->link($clienteLigaco->user->nome, ['controller' => 'Users', 'action' => 'view', $clienteLigaco->user->id]) : '' ?></td>
                            </tr>
                            <tr>
                                <th><?= __('Id') ?></th>
                                <td><?= $this->Number->format($clienteLigaco->id) ?></td>
                            </tr>
                            <tr>
                                                                <th><?= __('Dt. Criação') ?></th>
                                                                <td><?= h($clienteLigaco->created) ?></td>
                            </tr>
                            <tr>
                                                                <th><?= __('Dt. Modificação') ?></th>
                                                                <td><?= h($clienteLigaco->modified) ?></td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>

    <div class="ibox float-e-margins">
        <div class="ibox-title">
            <h3><?= __('Related Cliente Ligacoes') ?></h3>
        </div>
        <div class="ibox-content">
            <?php if (!empty($clienteLigaco->child_cliente_ligacoes)): ?>
            <div class="table-responsive">
                <table class="table table-hover">
                <tr>
                        <th><?= __('Id') ?></th>
                        <th><?= __('Cliente Id') ?></th>
                        <th><?= __('Parent Id') ?></th>
                        <th><?= __('Grau Id') ?></th>
                        <th><?= __('Situacao Id') ?></th>
                        <th><?= __('Created') ?></th>
                        <th><?= __('User Id') ?></th>
                        <th><?= __('Modified') ?></th>
                        <th class="actions"><?= __('Actions') ?></th>
                </tr>
                <?php foreach ($clienteLigaco->child_cliente_ligacoes as $childClienteLigacoes): ?>
                <tr>
                    <td><?= h($childClienteLigacoes->id) ?></td>
                    <td><?= h($childClienteLigacoes->cliente_id) ?></td>
                    <td><?= h($childClienteLigacoes->parent_id) ?></td>
                    <td><?= h($childClienteLigacoes->grau_id) ?></td>
                    <td><?= h($childClienteLigacoes->situacao_id) ?></td>
                    <td><?= h($childClienteLigacoes->created) ?></td>
                    <td><?= h($childClienteLigacoes->user_id) ?></td>
                    <td><?= h($childClienteLigacoes->modified) ?></td>
                    <td class="actions">
                        <?= $this->Html->link($this->Html->icon('list-alt'), ['controller' => 'ClienteLigacoes','action' => 'view', $childClienteLigacoes->id],['data-toggle'=>'tooltip','data-placement'=>'bottom','title'=>'Detalhes','escape' => false,'class'=>'btn btn-xs btn-info']) ?>
                        <?= $this->Html->link($this->Html->icon('pencil'), ['controller' => 'ClienteLigacoes','action' => 'edit', $childClienteLigacoes->id],['data-toggle'=>'tooltip','data-placement'=>'bottom','title'=>'Editar','escape' => false,'class'=>'btn btn-xs btn-primary']) ?>
                        <?= $this->Form->postLink($this->Html->icon('remove'), ['controller' => 'ClienteLigacoes','action' => 'delete', $childClienteLigacoes->id], ['confirm' => __('Você tem certeza que deseja excluir o registro # {0}?', $clienteLigaco->id),'data-toggle'=>'tooltip','data-placement'=>'bottom','title'=>'Deletar','escape' => false,'class'=>'btn btn-xs btn-danger']) ?>
                    </td>
                </tr>
                <?php endforeach; ?>
            </table>
            </div>
            <?php endif; ?>
        </div>
    </div>
</div>
</div>
</div>
</div>